/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List admin/staff (type=admin) or partner-portal (type=partner) users */
        get: operations["AdminUsersController_list"];
        put?: never;
        /** Create an admin/staff user (super_admin only) */
        post: operations["AdminUsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an account (self / last super_admin blocked) */
        delete: operations["AdminUsersController_remove"];
        options?: never;
        head?: never;
        /** Edit an account (name/email/roles/partner/active/password) */
        patch: operations["AdminUsersController_update"];
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin login — sets the session cookie (admin audience only) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out of the admin audience (keeps a partner session) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current admin session user (401 for a non-admin session) */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the current session user’s password (clears mustChangePassword) */
        post: operations["ChangePasswordController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List partners (for the "pick existing partner" dropdown) */
        get: operations["AdminPartnersController_list"];
        put?: never;
        /** Create a partner entity (super_admin only) */
        post: operations["AdminPartnersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners/{id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a partner-portal user linked to this partner */
        post: operations["AdminPartnersController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners/{id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an external API key for this partner — rawKey returned ONCE */
        post: operations["AdminPartnersController_createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List import batches */
        get: operations["ImportController_list"];
        put?: never;
        /** Upload a CSV/XLSX for a period — parsed asynchronously */
        post: operations["ImportController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import status/progress (also streamed via Socket.IO /rt) */
        get: operations["ImportController_getById"];
        put?: never;
        post?: never;
        /** Rollback a whole import batch (queued) */
        delete: operations["ImportController_rollback"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 31-day deposit pivot grid (rows = vehicles) */
        get: operations["GojekController_grid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One vehicle+day transaction breakdown (cell-click modal) */
        get: operations["GojekController_cell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/details/{detailId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One import detail row (prefill for the Edit form) */
        get: operations["GojekController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/edit-driver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit driver/plate on an import detail (assign plate to a manual-payment row, toggle setoran) */
        post: operations["GojekController_editDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard aggregates: summary cards + driver activity + charts */
        get: operations["GojekController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top/bottom 10 drivers by outstanding */
        get: operations["GojekController_performers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exceptions for a period */
        get: operations["GojekController_exceptions"];
        put?: never;
        /** Mark an exception (rental / maintenance / free-day) */
        post: operations["GojekController_createException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an exception */
        delete: operations["GojekController_deleteException"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/targets/{plate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read driver/target metadata for a plate */
        get: operations["TargetsController_get"];
        /** Create/update driver/target metadata (upsert by plate) */
        put: operations["TargetsController_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/grab/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 31-day earnings pivot grid (composite key plate|city|driver) */
        get: operations["GrabController_grid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/grab/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whole-month performance detail for one driver (eye modal) */
        get: operations["GrabController_cell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/grab/performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top/bottom 10 by total earning collected */
        get: operations["GrabController_performers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Partner portal login — sets the session cookie */
        post: operations["PortalController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PortalController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current partner user + partner profile */
        get: operations["PortalController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner metrics/summary widgets (own data only) */
        get: operations["PortalController_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own orders (paginated, filterable) */
        get: operations["PortalController_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/orders/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export own orders (?format=pdf|xlsx) */
        get: operations["PortalController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One own order detail (403 for another partner’s order) */
        get: operations["PortalController_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/plates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own registered plates (Daftarkan Plat) */
        get: operations["PortalPlatesController_list"];
        put?: never;
        /** Register a plate (nomor + Type) for the partner */
        post: operations["PortalPlatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/plates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit one own registered plate (nomor + Type) */
        put: operations["PortalPlatesController_update"];
        post?: never;
        /** Remove one own registered plate */
        delete: operations["PortalPlatesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/gojek/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Gojek 31-day deposit grid (scoped to registered plates) */
        get: operations["PortalFleetController_gojekGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/gojek/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Gojek vehicle+day breakdown */
        get: operations["PortalFleetController_gojekCell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/gojek/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Gojek dashboard aggregates (cards + driver activity + charts) */
        get: operations["PortalFleetController_gojekSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/grab/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Grab earnings grid (scoped to registered plates) */
        get: operations["PortalFleetController_grabGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/grab/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Grab driver whole-month performance detail */
        get: operations["PortalFleetController_grabCell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/v1/pricelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route/car pricelist for the authenticated partner */
        get: operations["PricelistController_quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order history for the authenticated partner */
        get: operations["PartnerOrdersController_list"];
        put?: never;
        /** Create an order (replaces legacy GET /partner/v1/order/create) */
        post: operations["PartnerOrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order's detail (own orders only — 404 for any other order) */
        get: operations["PartnerOrdersController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateAdminUserDto: {
            /** @example finance@fleet-taxi.id */
            email: string;
            /** @example Budi Finance */
            fullName: string;
            /** @example initial-password */
            password: string;
            /**
             * @description One or more staff roles (admin, finance, super_admin)
             * @example [
             *       "admin"
             *     ]
             */
            roles: ("admin" | "finance" | "super_admin")[];
        };
        UpdateUserDto: {
            email?: string;
            fullName?: string;
            /** @description Enable/disable login */
            isActive?: boolean;
            /** @description Admin/staff roles */
            roles?: ("admin" | "finance" | "super_admin")[];
            /** @description Move a partner-portal user to another partner org */
            partnerId?: number;
            /** @description Reset password (forces change on next login) */
            password?: string;
        };
        LoginDto: {
            /** @example admin@fleet-taxi.id */
            email: string;
            /** @example ******** */
            password: string;
        };
        ChangePasswordDto: {
            /** @example current-password */
            currentPassword: string;
            /** @example new-strong-password */
            newPassword: string;
        };
        CreatePartnerDto: {
            /**
             * @description Unique partner code (stored uppercase)
             * @example BHISA
             */
            code: string;
            /** @example Bhisa Shuttle */
            name: string;
            /**
             * @description shuttle | hotel | ...
             * @example shuttle
             */
            type?: string;
        };
        CreatePartnerUserDto: {
            /** @example portal@bhisa.example */
            email: string;
            /** @example Bhisa Portal User */
            fullName: string;
            /** @example initial-password */
            password: string;
        };
        CreateApiKeyDto: {
            /** @example Production integration key */
            label?: string;
            /**
             * @description Scopes granted to the key
             * @example [
             *       "pricelist",
             *       "order:create",
             *       "order:read"
             *     ]
             */
            scopes?: string[];
            /**
             * @description Requests per minute
             * @example 60
             */
            rateLimit?: number;
        };
        EditDriverDto: {
            /** @description fleet_import_details.id (manual-row / single-detail edit) */
            detailId?: number;
            /** @description Existing normalized plate (by-plate edit across a period) */
            plate?: string;
            /** @description Partition period month (1..12) */
            month?: number;
            /** @description Partition period year */
            year?: number;
            driverName?: string;
            /** @description New plate to assign (normalized server-side) */
            vehiclePlate?: string;
            /** @description 1 = Masuk Setoran, 0 = Tidak Masuk Setoran (manual payment only) */
            isManualPaymentSetoran?: number;
            /** @description Reason shown when Tidak Masuk Setoran */
            manualPaymentNote?: string;
        };
        CreateExceptionDto: {
            /** @example B1234XY */
            vehiclePlate: string;
            /**
             * @description YYYY-MM-DD
             * @example 2026-07-10
             */
            exceptionDate: string;
            /** @example Perbaikan bengkel */
            keterangan?: string;
            /**
             * @description true = bebas setoran (reduces target days)
             * @default false
             */
            isBebasSetoran: boolean;
        };
        UpsertTargetDto: {
            /** @description Daily target in integer rupiah (Gojek) */
            fleetTarget?: number;
            rentalPartner?: string;
            /** @description Gojek only */
            deliveryBatch?: string;
            /** @description Gojek only */
            serviceArea?: string;
            vehicleType?: string;
            /** @description Gojek only */
            regionId?: number;
            /** @description Grab only */
            city?: string;
        };
        CreatePlateDto: {
            /**
             * @description Nomor plat (as entered)
             * @example B 1793 SCP
             */
            plateNumber: string;
            /**
             * @description Type (jenis kendaraan)
             * @example Premium - BYD M6
             */
            vehicleType?: string;
        };
        CreatePartnerOrderDto: {
            /**
             * @description Pool code (whitelisted)
             * @example BHISA_CAWANG
             */
            pickupCode: string;
            /** @example EVISTA_HALIM */
            destinationCode: string;
            /** @example 1 */
            carTypesId: number;
            /**
             * @description ISO 8601, or "YYYY-MM-DD HH:mm:ss" interpreted as Asia/Jakarta
             * @example 2026-07-10 09:00:00
             */
            pickupAt: string;
            /** @description Free-form passenger details object (stored as JSON; size-bounded) */
            passengerDetails?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUsersController_list: {
        parameters: {
            query?: {
                /** @description admin = staff users (no partner); partner = partner-portal users */
                type?: "admin" | "partner";
                page?: string;
                pageSize?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangePasswordController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPartnersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPartnersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartnerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPartnersController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartnerUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPartnersController_createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "gojek" | "grab";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "gojek" | "grab";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @example 7 */
                    month: number;
                    /** @example 2026 */
                    year: number;
                };
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "gojek" | "grab";
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportController_rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "gojek" | "grab";
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_grid: {
        parameters: {
            query: {
                month: number;
                year: number;
                plate?: string;
                rentalPartner?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_cell: {
        parameters: {
            query: {
                month: number;
                year: number;
                /** @description Row key: normalized plate or manual_<detailId> */
                plate: string;
                day: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_detail: {
        parameters: {
            query?: {
                month?: number;
                year?: number;
            };
            header?: never;
            path: {
                detailId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_editDriver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditDriverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_summary: {
        parameters: {
            query: {
                month: number;
                year: number;
                day?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_performers: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_exceptions: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_createException: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExceptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GojekController_deleteException: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TargetsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "gojek" | "grab";
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TargetsController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "gojek" | "grab";
                plate: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTargetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrabController_grid: {
        parameters: {
            query: {
                month: number;
                year: number;
                plate?: string;
                rentalPartner?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrabController_cell: {
        parameters: {
            query: {
                month: number;
                year: number;
                /** @description plate|city|driver */
                compositeKey: string;
                day?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GrabController_performers: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_orders: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                tripStatus?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_export: {
        parameters: {
            query: {
                format: "xlsx" | "pdf";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalPlatesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalPlatesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalPlatesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalPlatesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalFleetController_gojekGrid: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalFleetController_gojekCell: {
        parameters: {
            query: {
                month: number;
                year: number;
                /** @description Row key: normalized plate or manual_<detailId> */
                plate: string;
                day: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalFleetController_gojekSummary: {
        parameters: {
            query: {
                month: number;
                year: number;
                day?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalFleetController_grabGrid: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalFleetController_grabCell: {
        parameters: {
            query: {
                month: number;
                year: number;
                /** @description plate|city|driver */
                compositeKey: string;
                day?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricelistController_quote: {
        parameters: {
            query: {
                pickupCode: string;
                destinationCode: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartnerOrdersController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartnerOrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartnerOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartnerOrdersController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
