/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/fleet/gojek/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gojek 31-day pivot grid */
        get: operations["getGojekGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One vehicle+day breakdown (cell-click modal) */
        get: operations["getGojekCell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/grab/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grab 31-day pivot grid (composite plate|city|driver) */
        get: operations["getGrabGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/grab/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One Grab vehicle+day breakdown */
        get: operations["getGrabCell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
            };
            cookie?: never;
        };
        /** List import batches */
        get: operations["listImports"];
        put?: never;
        /** Upload CSV/XLSX for a period → enqueue async parse */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
                id: number;
            };
            cookie?: never;
        };
        /** Import status/progress (HTTP poll fallback for Socket.IO) */
        get: operations["getImportStatus"];
        put?: never;
        post?: never;
        /** Rollback a whole import batch (queued) */
        delete: operations["rollbackImport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/targets/{plate}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
                plate: string;
            };
            cookie?: never;
        };
        /** Read driver + target metadata */
        get: operations["getTarget"];
        /** Edit driver + target metadata */
        put: operations["updateTarget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exceptions for a period */
        get: operations["listExceptions"];
        put?: never;
        /** Create/mark an exception (rental/maintenance/free-day) */
        post: operations["createException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an exception */
        delete: operations["deleteException"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/{platform}/performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top/bottom performers for the period */
        get: operations["getPerformers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Partner portal login → sets HTTP-only session cookie */
        post: operations["partnerLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End session */
        post: operations["partnerLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current partner user + partner profile */
        get: operations["partnerMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner metrics/summary widgets */
        get: operations["partnerDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own orders (paginated, filterable) */
        get: operations["partnerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/orders/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export own orders as PDF or Excel (server-generated) */
        get: operations["partnerOrdersExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One own order detail */
        get: operations["partnerOrderDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fleet/gojek/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly aggregates for the admin dashboard (global summary + driver activity) */
        get: operations["getGojekSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin/super-admin login (separate surface from partner portal) */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End admin session */
        post: operations["adminLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current admin user (401 if not an admin session) */
        get: operations["adminMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/plates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own registered plates */
        get: operations["listPartnerPlates"];
        put?: never;
        /** Register a plate (nomor + Type) */
        post: operations["createPartnerPlate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/plates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one own registered plate */
        delete: operations["deletePartnerPlate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/gojek/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Gojek pivot grid (scoped) */
        get: operations["getPartnerGojekGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/gojek/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Gojek vehicle+day breakdown */
        get: operations["getPartnerGojekCell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/gojek/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Gojek dashboard aggregates */
        get: operations["getPartnerGojekSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/grab/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Grab earnings grid (scoped) */
        get: operations["getPartnerGrabGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/portal/fleet/grab/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Grab driver performance detail */
        get: operations["getPartnerGrabCell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            page: number;
            pageSize: number;
            total: number;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
                details?: {
                    field: string;
                    message: string;
                }[];
            };
        };
        DayCellValue: {
            day: number;
            /**
             * Format: int64
             * @description integer rupiah, backend-computed
             */
            amount: number;
            hasManualUncounted?: boolean;
            hasException?: boolean;
        };
        FleetRowSummary: {
            /** Format: int64 */
            dailyTarget: number;
            /** Format: int64 */
            monthlyTarget: number;
            /** Format: int64 */
            totalDeduction: number;
            /** Format: int64 */
            outstanding: number;
        };
        FleetRow: {
            /** @description backend-normalized [A-Z0-9] pivot key (or manual_<detailId>) */
            plateNorm: string;
            plateRaw: string;
            driverName: string;
            rentalPartner?: string | null;
            /** @description sparse map keyed by day 1..31 */
            days: {
                [key: string]: components["schemas"]["DayCellValue"];
            };
            summary: components["schemas"]["FleetRowSummary"];
        };
        FleetGrid: {
            month: number;
            year: number;
            daysInMonth: number;
            rows: components["schemas"]["FleetRow"][];
        };
        CellBreakdownItem: {
            /** Format: date */
            transactionDate: string;
            /** @enum {string} */
            type: "deduction" | "due" | "manual";
            /** Format: int64 */
            amount: number;
            referenceId?: string | null;
            /** @description 1=counted, 0=uncounted (Tidak Masuk Setoran), null=n/a */
            isManualPaymentSetoran?: number | null;
            manualPaymentNote?: string | null;
        };
        CellBreakdown: {
            plateNorm: string;
            day: number;
            /** Format: int64 */
            total: number;
            items: components["schemas"]["CellBreakdownItem"][];
        };
        GrabDayCell: {
            /**
             * Format: int64
             * @description total_earning_collected summed per day, integer rupiah
             */
            earning: number;
        };
        GrabRowSummary: {
            /** Format: int64 */
            earning: number;
            /** Format: int64 */
            incentive: number;
            /** Format: int64 */
            driverFare: number;
            rides: number;
            onlineHours: number;
            bookings: number;
            cancellations: number;
            fulfillmentRate: number;
        };
        GrabRow: {
            /** @description plate|city|driver */
            compositeKey: string;
            plateNumber: string;
            city: string;
            driverName: string;
            /** @description sparse map keyed by day 1..31 */
            days: {
                [key: string]: components["schemas"]["GrabDayCell"];
            };
            summary: components["schemas"]["GrabRowSummary"];
        };
        GrabGrid: {
            month: number;
            year: number;
            daysInMonth: number;
            rows: components["schemas"]["GrabRow"][];
        };
        GrabCellBreakdownItem: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            totalEarningCollected: number;
            /** Format: int64 */
            totalIncentive?: number;
            /** Format: int64 */
            driverFare?: number;
            /** Format: int64 */
            tollAndOthers?: number;
            totalRides?: number;
            totalBookings?: number;
            totalOnlineHours?: number;
            cancelByDriver?: number;
            fullfilmentRate?: number;
        };
        GrabCellBreakdown: {
            compositeKey: string;
            day: number;
            /** Format: int64 */
            total: number;
            items: components["schemas"]["GrabCellBreakdownItem"][];
        };
        ImportBatch: {
            /** Format: int64 */
            id: number;
            filename: string;
            periodMonth: number;
            periodYear: number;
            /** @enum {string} */
            status: "pending" | "processing" | "done" | "failed";
            totalRows: number;
            processed?: number | null;
            percent?: number | null;
            importedBy?: string | null;
            error?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        FleetTarget: {
            vehiclePlate: string;
            vehiclePlateNorm: string;
            driverName?: string | null;
            vehicleType?: string | null;
            /**
             * Format: int64
             * @description integer rupiah daily target; null/0 → backend infers
             */
            fleetTarget?: number | null;
            rentalPartner?: string | null;
            deliveryBatch?: string | null;
            serviceArea?: string | null;
            /** Format: int64 */
            regionId?: number | null;
            /** @description grab only */
            city?: string | null;
        };
        FleetTargetUpdate: {
            driverName?: string;
            vehicleType?: string;
            /** Format: int64 */
            fleetTarget?: number;
            rentalPartner?: string;
            deliveryBatch?: string;
            serviceArea?: string;
            /** Format: int64 */
            regionId?: number;
            city?: string;
        };
        FleetException: {
            /** Format: int64 */
            id: number;
            vehiclePlate: string;
            /** Format: date */
            exceptionDate: string;
            keterangan?: string | null;
            isBebasSetoran: boolean;
        };
        FleetExceptionCreate: {
            vehiclePlate: string;
            /** Format: date */
            exceptionDate: string;
            keterangan?: string;
            /** @default false */
            isBebasSetoran: boolean;
        };
        Performer: {
            /** @description plateNorm (gojek) or compositeKey (grab) */
            key: string;
            label: string;
            driverName?: string | null;
            /** Format: int64 */
            total: number;
        };
        PartnerMe: {
            /** Format: int64 */
            id: number;
            email: string;
            fullName: string;
            roles: string[];
            partner?: {
                /** Format: int64 */
                id: number;
                code: string;
                name: string;
                type: string;
            } | null;
        };
        PartnerDashboard: {
            totalOrders: number;
            ordersThisMonth: number;
            /** Format: int64 */
            revenueThisMonth: number;
            ordersByDay: {
                /** Format: date */
                date: string;
                count: number;
            }[];
            ordersByStatus: {
                status: string;
                count: number;
            }[];
        };
        Order: {
            /** Format: int64 */
            id: number;
            orderNumber: string;
            orderType?: string | null;
            tripStatus: string;
            pickupCode?: string | null;
            destinationCode?: string | null;
            /** Format: int64 */
            carTypesId?: number | null;
            /** Format: date-time */
            pickupAt: string;
            /**
             * Format: int64
             * @description integer rupiah
             */
            basicPrice: number;
            passengerDetails?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
        };
        PartnerPlate: {
            id: number;
            plateNumber: string;
            plateNumberNorm: string;
            vehicleType?: string | null;
        };
        PartnerPlateCreate: {
            plateNumber: string;
            vehicleType?: string;
        };
    };
    responses: {
        /** @description Standard error envelope (PROJECT-BRIEF.md §6) */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Platform: "gojek" | "grab";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGojekGrid: {
        parameters: {
            query: {
                month: number;
                year: number;
                rentalPartner?: string[];
                plate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pivot grid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGojekCell: {
        parameters: {
            query: {
                /** @description plateNorm (or manual_<detailId> synthetic key) */
                plate: string;
                day: number;
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Day breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGrabGrid: {
        parameters: {
            query: {
                month: number;
                year: number;
                rentalPartner?: string[];
                plate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pivot grid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGrabCell: {
        parameters: {
            query: {
                /** @description plate|city|driver */
                compositeKey: string;
                day: number;
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Day breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listImports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import batches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ImportBatch"][];
                        meta?: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    month: number;
                    year: number;
                };
            };
        };
        responses: {
            /** @description Batch created, parsing queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            /** Format: int64 */
                            importId: number;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getImportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import batch with progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ImportBatch"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rollbackImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollback queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            /** Format: int64 */
                            importId: number;
                            status: string;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["FleetTarget"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
                plate: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetTargetUpdate"];
            };
        };
        responses: {
            /** @description Updated target metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["FleetTarget"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExceptions: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exceptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["FleetException"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createException: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetExceptionCreate"];
            };
        };
        responses: {
            /** @description Created exception */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["FleetException"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteException: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            deleted: boolean;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPerformers: {
        parameters: {
            query: {
                month: number;
                year: number;
                limit?: number;
            };
            header?: never;
            path: {
                platform: components["parameters"]["Platform"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top/bottom performers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PartnerMe"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            loggedOut: boolean;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PartnerMe"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PartnerDashboard"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerOrders: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                tripStatus?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["Order"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerOrdersExport: {
        parameters: {
            query: {
                format: "pdf" | "xlsx";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    partnerOrderDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["Order"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGojekSummary: {
        parameters: {
            query: {
                month: number;
                year: number;
                day?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly aggregates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: Record<string, never>;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Admin session user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    adminMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            401: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listPartnerPlates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered plates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PartnerPlate"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPartnerPlate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerPlateCreate"];
            };
        };
        responses: {
            /** @description Created plate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PartnerPlate"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deletePartnerPlate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: Record<string, never>;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPartnerGojekGrid: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pivot grid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPartnerGojekCell: {
        parameters: {
            query: {
                /** @description row key: normalized plate or manual_<id> */
                plate: string;
                day: number;
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Day breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPartnerGojekSummary: {
        parameters: {
            query: {
                month: number;
                year: number;
                day?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly aggregates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: Record<string, never>;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPartnerGrabGrid: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grab grid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPartnerGrabCell: {
        parameters: {
            query: {
                /** @description plate|city|driver */
                compositeKey: string;
                day?: number;
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Driver detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
